name: Build

on:
  push:
    branch:
      - master

env:
  SOURCEDIR: src
  APPNAME: main # Cambiar por el nombre de la app
  PYTHONFILENAME: main.py

jobs:
  buildWindows:
    name: Build for Windows
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: PyInstaller Windows
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: ${{ env.SOURCEDIR }}

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ env.APPNAME }}
        path: ${{ env.SOURCEDIR }}/dist/windows # or path/to/artifact
  
  buildMacOs:
    name: Build for MacOS

    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r ${{ env.SOURCEDIR }}/requirements.txt
    
    - name: Build with pyinstaller
      run: pyinstaller -F --distpath ${{ env.SOURCEDIR }}/dist/macos ${{ env.SOURCEDIR }}/${{ env.PYTHONFILENAME }}

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ env.APPNAME }}
        path: ${{ env.SOURCEDIR }}/dist/macos # or path/to/artifact

