name: Build

on:
  push:
    branch:
      - master

jobs:
  buildWindows:
    name: Build for Windows
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: PyInstaller Windows
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src

    - uses: actions/upload-artifact@v2
      with:
        name: my-exe
        path: src/dist/windows # or path/to/artifact
  
  buildMacOs:
    name: Build for MacOS

    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
    
    - name: Build with pyinstaller
      run: pyinstaller -F -n my-app.app main.py

    - uses: actions/upload-artifact@v2
      with:
        name: my-app
        path: src/dist/macos # or path/to/artifact

